apiVersion: v1
kind: Service
metadata:
  name: goauth-service
  namespace: authentication
  labels:
    name: goauth-service
spec:
  type: LoadBalancer
  ports:
    - name: goauthport
      port: 2011
      targetPort: 2011
  selector:
    app: goauth
